# -*- coding: utf-8 -*-
"""
create on 2021-04-16 10:16 上午

author @guorui
"""
"""
Django settings for hm_report project.

Generated by 'django-admin startproject' using Django 2.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os


CONFIG_NAME = "dev"
# 本地开发环境
ENV_NODE = "localhost"
# 前端身份验证字段名
FE_ACCESS_TOKEN_KEY = 'Accesstoken'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^wr109xs*pc)3f3^b$$eb*w1)luq*fo&gd)l$fqcry7rwygair'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
INTERNAL_IPS = [
    # ...
    '127.0.0.1',
    # ...
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'debug_toolbar',
    'rest_framework',
]

MIDDLEWARE = [
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'weight_report.urls'
# WSGI_APPLICATION = 'weight_report.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
mongo_database = 'htf-spider'
username = 'htf_spider',
password = 'htf-spider-pass',
host = 'mongodb://admin:qwerty@localhost/production'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'wenzhi_reader',
        'HOST': '192.168.1.19',
        'POST': 3306,
        'USER': 'root',
        'PASSWORD': 'haima'
    }
}
# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://47.92.96.14:6888/11",
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#             "PASSWORD": "jiangshan"
#         }
#     }
# }

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'verbose': {
#             'format': '[%(asctime)s] [%(levelname)s] %(message)s'
#         },
#     },
#     'handlers': {
#         # 输出日志的控制台
#         'console': {
#             'level': 'INFO',
#             'class': 'logging.StreamHandler',
#             'formatter': 'verbose'
#         },
#         # 输出日志到文件，按日期滚动
#         'behavior': {
#             'level': 'INFO',
#             'class': 'logging.handlers.RotatingFileHandler',
#             'filename': os.path.join(BASE_DIR, 'logs/behavior.log'),
#             'maxBytes': 50 * 1024 * 1024,
#             'encoding': 'utf-8',
#             'backupCount': 50,
#         },
#         'file': {
#             'level': 'DEBUG',
#             'class': 'logging.handlers.TimedRotatingFileHandler',
#             'filename': os.path.join(BASE_DIR, 'logs/manage.log'),
#             'when': 'midnight',
#             'interval': 1,
#             'backupCount': 100,
#             'formatter': 'verbose'
#         }
#     },
#     'loggers': {
#         # 不同的logger
#         'behavior': {
#             'handlers': ['behavior'],
#             'propagate': False,
#         },
#         'django': {
#             'handlers': ['console', 'file'],
#             'propagate': False,
#         },
#     },
# }

REST_FRAMEWORK = {
    'DATETIME_FORMAT': '%Y-%m-%d %X',
    'EXCEPTION_HANDLER': 'common.exception.custom_exception_handler',
}

# 跨域增加忽略
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = ()

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'VIEW',
)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# mongo
MONGO_HOST = '192.168.1.19'
MONGO_PORT = 27017
MONGO_DBNAME = 'htf_spider'
MONGO_CONNECT = False


